# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea5d61fc383453e667c08186728617ef3471f2bacf1185e6855406bc2a45c7b183bff5140a562f4fa6dad10ffffed9c5fce6d5ddad78aab1f13fc1eb21b6061c

test:
  secret_key_base: f11c975525b02963c0fb2ed77bd35c22f69a7363712aa53c7a13144d8a602622f6594aa89cfb929a82c3acdc0ae7cf31478e7bf71217162a7445e6a5b24c2c64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
